server:
  port: 8888
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      acknowledge-mode: manual
    virtual-host: /
    publisher-confirms: true
    connection-timeout: 2