server:
  port: 1818
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      acknowledge-mode: manual
    virtual-host: /
    publisher-confirms: true
    connection-timeout: 2
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/squeue
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  data:
#    mongodb:
#      database: test

#squeue:
#  mq:
#    binds:
#      - exchange: receive_exchange
#        type: topic
#        squeue: receive_queue
#        routingkey: receive_key


mybatis:
  mapperLocations: 'classpath:mapper/*.xml'