server:
  port: 0
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      acknowledge-mode: manual
    virtual-host: /
    publisher-confirms: true
    connection-timeout: 2
queue:
  mq:
    binds:
      - exchange: receive_exchange
        type: topic
        queue: receive_queue
        routingkey: receive_key
    consumer:
      - queue: receive_queue
        listener: receive
#      - exchange: ga
#        type: direct
#        queue: queue2
#        routingkey: key1